default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("PG_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("PG_USERNAME") { 'postgres' } %>
  password: <%= ENV["PG_PASSWORD"] %>
  port: <%= ENV.fetch("PG_PORT") { 5432 } %>

development:
  <<: *default
  database: recettes_api_development

test:
  <<: *default
  database: recettes_api_test

production:
  <<: *default
  database: recettes_api_production
  username: <%= ENV["PG_PRODUCTION_USERNAME"] %>
  password: <%= ENV["PG_PRODUCTION_PASSWORD"] %>
